### ISSUE TITLE
Deploy error /tags/refs/heads' is not a directory

### ISSUE THREAD

**Issue by tatthien** [10up/action-wordpress-plugin-deploy#36]
Hi,

I get an error while deploying. It says:

```
svn: E155010: Path '/github/svn-{my-plugin-slug}/tags/refs/heads' is not a directory
``` 

Here is the deployment log:
https://github.com/tatthien/flat-preloader/runs/611100008?check_suite_focus=true

**Comment by dinhtungdu** [comment]
Hi @tatthien,

I notice that you aren't using git tag, can you switch to tag and try again?

> This Action commits the contents of your Git tag to the WordPress.org plugin repository using the same tag name.

**Comment by tatthien** [comment]
It works.
Thanks for helping.

**Comment by MichaelFBA** [comment]
Can we simply use push on master branch which creates a tag during the previous step?
```
name: Deploy to WordPress.org
on:
  push:
    branches:
      - master
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Build # Remove or modify this step as needed
      run: |
        npm ci
        npm version patch

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: <OUR_PLUGIN>
```
